// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvjowvxlqqmvwkqqqxsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2am93dnhscXFtdndrcXFxeHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDUyODUsImV4cCI6MjA3MDY4MTI4NX0.mKQ2th_wPCsZ7xdr7u6PHkNxQOsVNgCdC-jIvDgmt2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});